apiVersion: app/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: golang
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      name: golang-2
      labels:
        app: myapp
    spec:
      containers:
        - name: golang
          image: sharvis8/simplegolang:latest
